---
title: "pmtct eac"
author: "Mitch"
date: "2024-04-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
libraries
```{r}
pacman::p_load(tidyverse, lubridate, haven, writexl,readxl,zoo)
```
data 


```{r}
greencard <-read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetGreencard.sav") ###data from greencard

discontinued <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetprogram_discontinuation.sav") ####individual discontinued

drug <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetDrug_Prescriptions.sav") ###drug distribute 


lab <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetlab data.sav") ### labworks

address <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetaddress and intake.sav") ####individual personnal data

drugevent <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetDrug Event.sav") ###drug stat 

pending <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetvl_genxpert_cd4_request.sav") ###pending vl results

eac <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetEACs.sav") ###eacs done for client

ANC_Visit <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetANC_Visit.sav") ##anc visits within the facility

hts <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetHTS DATA.sav") ###Testing data

mch <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetMCH Enrollment.sav") ### enrolled in mch program

mch_pn <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetMCH Postnatal.sav")  ### postnatal clinic


hiv <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_datasetHIV enrollment.sav") ## positive for HIV


defaulter <- read_sav("\\\\ng-svr-fs/Hope-Data/Coptic_Hospitals_dataset/Defaulter_tracing.sav") ####missed appoint


```
active
```{r}
patient_visit<- greencard 

##clients who are active before the end of the month.
active <- patient_visit%>%
  select(patient_id,visit_date,next_appointment_date, mflcode,pregnancy_status,breastfeeding)%>%
  filter(visit_date <= as.Date("2024-05-31"))%>%
  arrange (desc(visit_date))%>%    ### arrange the data in descending order
  distinct(patient_id, mflcode, .keep_all = TRUE)%>%
  rename("last_visit_date" = "visit_date")

last_visit <- patient_visit%>%
  select(patient_id,visit_date,next_appointment_date, mflcode,pregnancy_status,breastfeeding)%>%
  filter(between(visit_date, as.Date("2024-05-01"), as.Date("2024-04-30"))) 


##IIT those scheduled to come within 30 days of the past month
IITkemr<- active %>%
  filter(next_appointment_date >= as.Date("2024-05-31")-28)

allpatient <- IITkemr[IITkemr$next_appointment_date >= IITkemr$last_visit_date,] ###clients who have a higher appointment date. 


####patients who have been discontinued 
disc <- discontinued%>%
  select(patient_id,visit_date,program_name,discontinuation_reason,mflcode)%>%
  filter(program_name == "HIV")%>%
  rename("disc_visit_date" = "visit_date")%>%
  separate(disc_visit_date,c("date_disc", "time_disc"),sep=" ") ###separate date and time


class(disc$date_disc) ##check class of date

disc$date_disc <- ymd(disc$date_disc) ##convert date in date variables

class(disc$date_disc) ###confirm class of date


adisc <- disc %>%
  filter(date_disc <= as.Date("2024-05-31")-28)%>%
  arrange (desc(date_disc))%>%    ### arrange the data in descending order
  distinct(patient_id, mflcode, .keep_all = TRUE)


allpatient <- left_join(allpatient,adisc, by = c("patient_id","mflcode"))

##clients who have never been discontinued from the program
act <- allpatient %>%
  filter(is.na(discontinuation_reason)) ####removing the patients discontinued

##client who have ever been discontinued but are returned to care. Thus their visit date is greater than their last discontinuation date

never_disc <- allpatient %>% 
  drop_na(discontinuation_reason)


rtt <- never_disc[never_disc$last_visit_date >= never_disc$date_disc,] ###those returned to care

rtt <- rtt %>%
  filter(discontinuation_reason != "Died")

active_clients <- rbind(act,rtt) %>%
  arrange(desc(last_visit_date))%>%
  distinct(patient_id, mflcode, .keep_all = TRUE)


#####when the clients started art
art_start <- drugevent%>%
  select(patient_id,mflcode,program,art_startdate)%>% ###get the regimen of all clients. allow to remove clients 
 filter(program == "HIV")%>%
  arrange(desc(art_startdate))%>%
  distinct(patient_id, mflcode, .keep_all = TRUE)


actpat <- inner_join(active_clients,art_start, by = c("patient_id","mflcode"))

actpat <- actpat %>%
  filter(art_startdate <= as.Date("2024-05-31"))

#### addition of Individual details
patid<- address %>%
  select(patient_id,unique_patient_no,given_name,middle_name,family_name,DOB,Gender, mflcode) %>%  ##patient key detail
  distinct(patient_id, mflcode, .keep_all = TRUE) ###remove any duplication


activecurr<-left_join(actpat, patid, by=c('patient_id'='patient_id', 'mflcode'='mflcode')) ###all visitors with their personal details


x_date <- as.Date("2024-05-31") ### using lubricate to assign a client date

activecurr$age <- trunc((activecurr$DOB %--% x_date) / years(1)) ### using lubricate to assign a client date


activecurr <- activecurr %>%
  select(patient_id,mflcode,unique_patient_no,given_name,middle_name,family_name,last_visit_date,next_appointment_date,pregnancy_status,breastfeeding,art_startdate,age)



###laboratory
laab <- lab %>%
  select(patient_id,mflcode,date_ordered,lab_test,test_result,date_test_requested)%>%
  filter(lab_test == "HIV VIRAL LOAD"|lab_test =="HIV VIRAL LOAD, QUALITATIVE" & date_ordered >= as.Date("2023-12-01"))%>%
  arrange(desc(date_ordered))%>%
  distinct(patient_id, mflcode, .keep_all = TRUE) ### get the latest lab result for clients valid results patients should have been bleed last 6 months. 


laab$test_result <- as.numeric(as.character(laab$test_result)) ###converting test_results into numeric for

class(laab$test_result) ###confirm class

pmtct <- left_join(activecurr,laab, by = c("patient_id","mflcode"))%>%
   filter(breastfeeding == "Yes"|pregnancy_status == "Yes")%>%
  unite(client_name, c("given_name","middle_name","family_name"), sep = " ")

Ngong <- left_join(activecurr,laab, by = c("patient_id","mflcode"))%>%
  filter(mflcode == 12905)

write_xlsx(Ngong, path = " tx curr.xlsx")

##those bleed but have pending results
vlpending <- pending %>%
  select(patient_id,vl_request_date,variablename,mflcode)%>%
  filter(vl_request_date>= as.Date("2023-12-01") & variablename =="HIV VIRAL LOAD"|variablename =="HIV VIRAL LOAD, QUALITATIVE")%>%
  arrange(desc(vl_request_date))%>%
  distinct(patient_id, mflcode, .keep_all = TRUE)

pmtct <- left_join(pmtct,vlpending, by = c("patient_id","mflcode"))


pmtct <- pmtct %>%
  mutate(age_group= case_when(age <=15 ~ "below 15",
                              age <=20 ~ "16-19 years",
                              age <=24 ~ "20-24 years",
                              age >=25 ~ "25 -80 years"))
  
###clients with high vl who had eacs done

dvl <- eac%>%
  select(patient_id,visit_date,session_number,mflcode,arv_adherence)%>%
  filter(visit_date>= as.Date("2023-12-01"))%>%
  arrange(visit_date)%>%
  group_by(patient_id,mflcode)%>%
  mutate(rank = 1:n()) ### create ranks of the different EAC done to the client

dvl <- dvl %>%
  arrange(desc(rank))%>%
  distinct(patient_id, mflcode, .keep_all = TRUE)

pmtct <- left_join(pmtct,dvl, by = c("patient_id","mflcode"))


repmtct <- pmtct %>%
  mutate(mflcode= recode (mflcode, "12881"= "Baraka Dispensary (Nairobi)",
                          "24563" = "Nairobi Adventist Hospital",
                          "13209"= "St Joseph W Dispensary (Westlands)", 
                          "13074"= "The Mater Hospital Mukuru",
                          "13057"= "Makadara Mercy Sisters Dispensary",
                          "17723"= "St Barkita Dispensary Utawala",
                          "12905"= "Coptic Hospital (Ngong Road)",
                          "15862"= "Coptic Nursing Home",
                          "18745"= "Comboni Sisters H Project VCT",
                          "12904"= "Coptic Medical Clinic",
                          "17683"= "St Raphaels Clinic",.default = NA_character_))
  

write_xlsx(repmtct, path = " may pmtct.xlsx")
```

